.gitignore
.travis.yml
6_object_wrap/nan/myobject.cc
6_object_wrap/nan/package.json
7_factory_wrap/nan/myobject.cc
8_passing_wrapped/nan/myobject.cc
README.md
async_work_thread_safe_function/node-api/package.json
package.json
test_all.js
thread_safe_function_round_trip/node-api/package.json

Update: 
https://travis-ci.org/gengjiawen/node-addon-examples
Now all test pass Node.js 8, 10.

add CI and fix current build issue

---

.travis.yml
build_with_cmake/README.md
build_with_cmake/napi/CMakeLists.txt
build_with_cmake/napi/hello.cc
build_with_cmake/napi/hello.js
build_with_cmake/napi/package.json
build_with_cmake/node-addon-api/CMakeLists.txt
build_with_cmake/node-addon-api/hello.cc
build_with_cmake/node-addon-api/hello.js
build_with_cmake/node-addon-api/package.json

I've created a couple of example projects that show how to build N-API addons using CMake.js. Once this PR lands, I plan to add links to it, along with some narrative, to https://github.com/nodejs/abi-stable-node/issues/381 and https://github.com/nodejs/node-addon-api/issues/445.

Build with cmake

---

.travis.yml

Related: https://github.com/nodejs/node-addon-examples/pull/116#issuecomment-539298607

lock cmake-js to 5 for Node.js 8 compatibility

---

3_callbacks/nan/addon.cc

Deprecated wrappers around the legacy `node::MakeCallback()` APIs, using the `AsyncResource::runInAsyncScope`

using AsyncResource::runInAsyncScope invoke callback in the nan of 3_callbacks file

---

.github/workflows/nodejs.yml
.travis.yml
6_object_wrap/node-addon-api/myobject.cc
6_object_wrap/node-addon-api/myobject.h
6_object_wrap/node-addon-api/package.json
7_factory_wrap/node-addon-api/myobject.cc
7_factory_wrap/node-addon-api/myobject.h
7_factory_wrap/node-addon-api/package.json
8_passing_wrapped/node-addon-api/addon.cc
8_passing_wrapped/node-addon-api/myobject.cc
8_passing_wrapped/node-addon-api/myobject.h
8_passing_wrapped/node-addon-api/package.json

This removes global static references from the examples, so that they
might work with worker threads.

make node-addon-api examples context-sensistive

---

6_object_wrap/node-addon-api/myobject.cc
7_factory_wrap/node-addon-api/myobject.cc
8_passing_wrapped/node-addon-api/myobject.cc
async_pi_estimate/node-addon-api/async.cc
function-reference-demo/node-addon-api/src/native-addon.cc
inherits_from_event_emitter/node-addon-api/src/native-emitter.cc

This PR removes the unneeded ` Napi::HandleScope` objects as identified in https://github.com/nodejs/node-addon-examples/issues/135 and https://github.com/nodejs/node-addon-examples/issues/142.

Remove unneeded Napi::HandleScope objects

---

.github/workflows/website.yml

This GitHub Action file rebuilds and publishes the Gatsby tutorial website to the `gh-pages` branch whenever there is a merge to `master`. 
This is related to https://github.com/nodejs/abi-stable-node/issues/391

Add GitHub Action to rebuild and publish website

---

README.md

This PR adds a link to the N-API tutorial website to the repo's README file.

add link to the n-api tutorial website

---

build_with_cmake/node-addon-api/CMakeLists.txt

Removes one line of CMakeLists.txt config file by using regex to run both replaces at one time.

simplify a little Cmake config with regex

---

README.md

Clarify that examples are primarily maintained for
N-API and node-addon-api.
Signed-off-by: Michael Dawson <mdawson@devrus.com>

doc: clarify focus is on n-api

---

website/docs/getting-started/migration.md

In https://nodejs.github.io/node-addon-examples/getting-started/migration
Following the tutorial, I got errors because `node-microtime` is already using `node-addon-api`. So I moved to the last commit before that change was added which is tag `v2.1.9`.

doc: Move to node-microtime tag in order to continue the tutorial

---

.github/workflows/website.yml
website/README.md
website/src/components/foundations/reset/styles/base.ts
website/src/components/foundations/reset/styles/reboot.ts
website/src/utils/types.ts

Also update the GitHub Action that builds the N-API Resource website.
This PR should be merged after the default branch of this repo changed from from `master` to `main`.
See https://github.com/nodejs/abi-stable-node/issues/421.

doc: update URL links from 'master' to 'HEAD'

---

build_with_cmake/node-addon-api/hello.cc

Very basic comments to help explain what the Env variable is doing and how the memory handoff is working.

Add some comments to the hello world example.

---

typed_array_to_native/node-addon-api/binding.gyp
typed_array_to_native/node-addon-api/index.js
typed_array_to_native/node-addon-api/package.json
typed_array_to_native/node-addon-api/typed_array_to_native.cc

This PR adds an example how to read and create TypedArray from native code using the C++ Node-API.

Examples to read and create TypedArray

---

async-iterator/node-addon-api/CMakeLists.txt
async-iterator/node-addon-api/example.cc
async-iterator/node-addon-api/index.js
async-iterator/node-addon-api/package.json
threadsafe-async-iterator/node-addon-api/CMakeLists.txt
threadsafe-async-iterator/node-addon-api/example.cc
threadsafe-async-iterator/node-addon-api/index.js
threadsafe-async-iterator/node-addon-api/package.json

An example as requested by https://github.com/nodejs/node-addon-api/issues/1171

Add node-addon-api async iterator example

---

.github/workflows/linter.yml
.github/workflows/nodejs.yml
.github/workflows/website.yml

This PR changes versions of components used in CI to the latest available:
-  node-version: [12.18.0, 14.x, 16.x] -> [14.x, 16.x, 18.x] _(version 12 is not supported anymore)_
- actions/checkout@v2 -> actions/checkout@v3
- actions/setup-node@v1 -> actions/setup-node@v3
- cmake-js@5.3.2 -> cmake-js@6.3.2

Update CI component versions

---

object-template-demo/README.md
object-template-demo/nan/binding.gyp
object-template-demo/nan/index.js
object-template-demo/nan/object-template-demo.cc
object-template-demo/nan/package.json
object-template-demo/napi/binding.gyp
object-template-demo/napi/index.js
object-template-demo/napi/node-api-common.h
object-template-demo/napi/object-template-demo.cc
object-template-demo/napi/package.json
object-template-demo/napi/proxy-template.cc
object-template-demo/napi/proxy-template.h

A new example that takes NAN namedinterceptors unit test that uses ObjectTemplate and then shows how to implement the same behavior using the JavaScript Proxy object. 
It is created to address issue https://github.com/nodejs/node-addon-api/issues/1114

Use JS Proxy to simulate V8 ObjectTemplate behavior

---

call-js-from-async-worker-execute/node-addon-api/binding.gyp
call-js-from-async-worker-execute/node-addon-api/index.js
call-js-from-async-worker-execute/node-addon-api/package.json
call-js-from-async-worker-execute/node-addon-api/src/binding.cc

This was asked for in https://github.com/nodejs/node-addon-api/issues/110#issuecomment-415536418 and https://github.com/nodejs/node-addon-api/issues/110#issuecomment-462586274. The solution was described in text in https://github.com/nodejs/node-addon-api/issues/110#issuecomment-415580690 but it would be better to have a code example that folks can refer to.
cc @mhdawson @NickNaso

example: add example for calling JS from `AsyncWorker::Execute()`

---

.github/workflows/nodejs.yml
.gitignore
1_hello_world/nan/hello.cc
2_function_arguments/nan/addon.cc
4_object_factory/nan/addon.cc
6_object_wrap/nan/myobject.cc
7_factory_wrap/nan/addon.cc
8_passing_wrapped/nan/addon.cc
package.json

Fixed build with newer Node.js versions, as `CreationContext` was deprecated for some versions of v8 and is now removed.
Added missing dependency "cmake-js", as `yarn test` fails without it.

Fixed build with newer Node.js versions

---

.github/workflows/test-website.yml
website/docs/special-topics/object-function-refs.md

Add a website build GitHub Action on each push and pull request to ensure that the website build is successful.

Add website tests

---

.github/dependabot.yml

We discussed in the node-api team meeting today and agreed to stop publishing the website.
Disabling checks on the website tools so that we don't get the noise.

disable checks for website that will no longer be published

---

.github/workflows/nodejs.yml

* windows-2019 no longer exists
* 16, 18 no longer maintain.

fix: use new config
